<a href="https://colab.research.google.com/github/Sudharshana-HG/priyanka-mar-02-/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving data_clean.csv to data_clean.csv

In [6]:
#Reading a .csv file
#CSV - Comma Separated Values
data = pd.read_csv("data_clean.csv")

In [10]:
data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [11]:
data.tail()

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    object
 5   Month       158 non-null    object
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 12.5+ KB

In [12]:
data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [14]:
data.isnull().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64